# build when tag is pushed

name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          npm update
          npm install

      - name: Build
        run: |
          npx @vscode/vsce package

      - name: Set artifact name
        run: echo "ARTIFACT_NAME=$(echo quicktypofix-*.vsix)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: "quicktypofix-*.vsix"

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$GITHUB_REF_NAME" --generate-notes

      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ASSET_PATH: ${{ env.ARTIFACT_NAME }}
        run: |
          gh release upload "$GITHUB_REF_NAME" "$ASSET_PATH" --repo "$GITHUB_REPOSITORY" --clobber
